<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MassTransit" Version="9.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fleet.Application\Fleet.Application.csproj" />
    <ProjectReference Include="..\Fleet.Infrastructure\Fleet.Infrastructure.csproj" />
    <ProjectReference Include="..\Fleet.Contracts\Fleet.Contracts.csproj" />
  </ItemGroup>

</Project>
